#!/bin/bash

function send_notification() {
	volume=$(pamixer --get-volume)
	dunstify -a "changevolume" -u low  -h int:value:"$volume" -i "$HOME/.config/scripts/icons/volume.png" "Volume: ${volume}%" -t 2000 -r 12345
    sleep 3 && dunstctl history-rm 12345
}

case $1 in
up)
	# Set the volume on (if it was muted)
	pamixer -u
	pamixer -i 5 --allow-boost
	send_notification $1
	;;
down)
	pamixer -u
	pamixer -d 5 --allow-boost
	send_notification $1
	;;
mute)
	pamixer -t
	if $(pamixer --get-mute); then
	    volume=$(pamixer --get-volume)
		dunstify -i volume-mute -a "changevolume" -t 2000 -r 12345 -u low "Muted" -h int:value:"$volume"
        sleep 3 && dunstctl history-rm 12345
	else
		send_notification up
	fi
	;;
esac
