#!/bin/bash
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color
err(){
	echo -e "${RED}ERROR:${NC} $1"
}
# make a function to show help
function show_help {
    echo -e "${GREEN}Usage:${NC} fitpdfs [OPTIONS] <file1> <file2> ..."
    echo "Options:"
    echo "-o <output_file> - output file name (default output.pdf)"
    echo "-w <width> - width of the output pdf (default 720)"
    echo "-h <height> - height of the output pdf (default 891)"
    echo "-q <quality> - quality of pdf (default low) [low, medium, high]"
    exit 0
}

if [[ $@ == "" ]]; 
then
    show_help
    exit 1
fi

output="output.pdf"
width=720
height=891
flag=0
files=""
quality="screen"
while getopts ":ho:w:h:q:" opt; do
    case $opt in
        h)
            show_help
            ;;
        \?)
            echo "Invalid option: -$OPTARG" >&2
            exit 1
            ;;
        o)
            output="$OPTARG"
            ;;
        w)
            width=$OPTARG
            ;;
        h)
            height=$OPTARG
            ;;
        q)
            echo "Quality: $OPTARG"
            case $OPTARG in
                low)
                    quality="screen"
                    ;;
                medium)
                    quality="ebook"
                    ;;
                high)
                    quality="printer"
                    ;;
                *)
                    echo "Invalid quality: $OPTARG" >&2
                    exit 1
                    ;;
            esac
            echo "Quality: $quality"
            ;;
        : )
            echo "Option -$OPTARG needs an argument." >&2
            show_help
            exit 1
            ;;
    esac
done
shift $(( OPTIND - 1 ))

files=()
for i in "$@"; do
    # for each file, replace spaces with \
    file=$(echo "$i" | sed "s/ /\ /g")
    if [[ $file =~ ^-.* ]]; then
        argv="$@"
        extra="${argv/${files[@]}}"
        # if extra is not empty then issue error
        if [[ ! $extra == "" ]]; then
            echo "$(err "Options come before files:$extra")" >&2
            show_help
            exit 1
        fi
        break
    fi
    if [[ ! $file =~ \.pdf$ ]]; then
        echo "$(err "Invalid file: $file")" >&2
        exit 1
    fi

    files+=("$file")
done

if [[ ${#files[@]} -eq 0 ]]; then
    show_help
    exit 1
fi

gs -o "$output" -sDEVICE=pdfwrite -dFIXEDMEDIA -dPDFFitPage \
    -dDEVICEWIDTHPOINTS="$width" -dDEVICEHEIGHTPOINTS="$height" \
    -dNOPAUSE -dCompatibilityLevel=1.4 -dPDFSETTINGS=/"$quality" \
    -dQUIET -dBATCH -dSAFER "${files[@]}"
