#!/bin/bash

common=$(pamixer --list-sources | grep "HyperX Cloud Flight Wireless Mono")
SOURCE_ID=$(cut -d ' ' -f1 <<< $common)
function send_notification() {
	volume=$(pamixer --source "$SOURCE_ID" --get-volume)
	dunstify -a "micvolume" -u low  -h int:value:"$volume" -i "$HOME/.config/scripts/icons/mic.png" "Volume: ${volume}%" -t 2000 -r 23456
    sleep 3 && dunstctl history-rm 23456
}

case $1 in
up)
    pamixer --source $SOURCE_ID -i 5
	send_notification $1
	;;
down)
    pamixer --source $SOURCE_ID -d 5
	send_notification $1
	;;
mute)
    pamixer --source $SOURCE_ID -t
	if $(pamixer --source $SOURCE_ID --get-mute); then
	    volume=$(pamixer --source $SOURCE_ID --get-volume)
		dunstify -i volume-mute -a "micvolume" -t 2000 -r 23456 -u low "Muted" -h int:value:"$volume" && sleep 2 && dunstctl history-rm 23456
	else
		send_notification up
	fi
	;;
get)
    pamixer --source $SOURCE_ID --get-volume-human
    ;;
esac
