#!/bin/bash

function send_notification() {
	volume=$(pamixer --source 1 --get-volume)
	dunstify -a "micvolume" -u low  -h int:value:"$volume" -i "$HOME/.config/scripts/icons/mic.png" "Volume: ${volume}%" -t 2000 -r 23456
    sleep 3 && dunstctl history-rm 23456
}

case $1 in
up)
    pamixer --source 1 -i 5
	send_notification $1
	;;
down)
    pamixer --source 1 -d 5
	send_notification $1
	;;
mute)
    pamixer --source 1 -t
	if $(pamixer --source 1 --get-mute); then
	    volume=$(pamixer --source 1 --get-volume)
		dunstify -i volume-mute -a "micvolume" -t 2000 -r 23456 -u low "Muted" -h int:value:"$volume" && sleep 2 && dunstctl history-rm 23456
	else
		send_notification up
	fi
	;;
esac
