#!/bin/sh
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias nvimrc='nvim ~/.config/nvim/'
alias zshrc='nvim ~/.config/zsh/'
alias i3rc='nvim ~/.config/i3/config'
alias i3statusrc='nvim ~/.config/i3status/config'
alias weather="curl wttr.in"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# exa as ls
alias ls="exa"

alias l='ls -a'
alias ll='ls -la'

alias parup="paru --bottomup"

alias vim="nvim"

alias i="GTK_THEME=Adwaita:dark vimiv"

alias z="zathura"

alias zaread="~/Public/zaread/zaread.sh"

# if not set, op runs in another shell
alias op=". op"
