#!/bin/sh
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export GOPATH=$HOME/.local/share/go
export PATH=$HOME/.fnm:$PATH
export PATH="$PATH:./node_modules/.bin"
export PATH="$JAVA_HOME/bin:$PATH"
export OPENMPI_PATH="/usr/lib64/openmpi"
export LS_COLORS="$($HOME/.config/scripts/dir2ls_colors $HOME/.config/ls_colors/dircolor)"
export LD_LIBRARY_PATH=/usr/lib/gcc/x86_64-pc-linux-gnu:$LD_LIBRARY_PATH
