#!/bin/sh
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias nvimrc='nvim ~/.config/nvim/'
alias zshrc='nvim ~/.config/zsh/'
alias i3rc='nvim ~/.config/i3/config'
alias i3statusrc='nvim ~/.config/i3status/config'
alias smn="~/.config/scripts/smn"
alias weather="smn -n '4856'"
alias clearpacman="sudo pacman -Sc"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'

# exa as ls
alias ls="eza --icons always"

alias l='ls -a'
alias ll='ls -la'

alias parup="paru --bottomup"

alias oldvim="vim"

alias vim="nvim"

alias sxiv="sxiv -a"
alias i="sxiv"

alias z="zathura"

alias zaread="~/.config/scripts/zaread.sh"

alias bc="bc ~/.config/bc/bclib -l -q"

# i use arch btw
alias btw="neofetch"

# reboot to avoid watchdog
alias reboot="/sbin/shutdown -r now"

# if not set, op runs in another shell
alias op=". op"

alias wpm="vim /mnt/backupfiles/wpm.txt"

alias lyrics="sptlrx --current 'bold,#c678dd,#282c34' --before '#61afef,faint,italic' --after '#61afef,faint'"

#alias exp_all="export $(grep -v '^#' .env | xargs)"
alias exp_all="set -o allexport; source .env; set +o allexport"

alias tree="tree -C"

alias diff="colordiff"

# ssh backspace
[ "$TERM" = "xterm-kitty" ] && alias ssh="kitty +kitten ssh"

# contiker
export CNG_PATH="/home/fots/development/contiki-ng"
alias contiker="xhost +'local:docker@' && docker run --privileged --sysctl net.ipv6.conf.all.disable_ipv6=0 --mount type=bind,source=$CNG_PATH,destination=/home/user/contiki-ng -e DISPLAY=$DISPLAY -e LOCAL_UID=$(id -u $USER) -e LOCAL_GID=$(id -g $USER) -v /tmp/.X11-unix:/tmp/.X11-unix -v /dev/bus/usb:/dev/bus/usb -ti contiker/contiki-ng"

# md2pdf, usage: md2pdf file.md -o file.pdf
alias md2pdf="pandoc -V geometry:margin=1in -V fontsize=14pt -V papersize:a5"

# xclip to clipboard
alias copy="xclip -selection clipboard"

alias gitsub="git submodule foreach git pull origin develop --recurse-submodules"

alias chat="docker exec -it ollama ollama run terminal-chat"

alias gs="git status"
alias gl="git log"
alias gd="git diff"
alias gc="git commit"
alias gp="git push"
alias gpl="git pull"
alias ga="git add"
