#!/bin/sh
HISTSIZE=1000000
SAVEHIST=1000000
export PATH="$HOME/.local/bin":$PATH
export MANPAGER='nvim +Man!'
export MANWIDTH=999
export PATH=$HOME/.cargo/bin:$PATH
export PATH=$HOME/.local/share/go/bin:$PATH
export GOPATH=$HOME/.local/share/go
export PATH=$HOME/.fnm:$PATH
export PATH="$PATH:./node_modules/.bin"
export JAVA_HOME="$(find /usr/lib/jvm -maxdepth 1 | grep openjdk | awk -F '-' '$2>count {count=$2; java_home=$0} END {print java_home}')"
export PATH="$JAVA_HOME/bin:$PATH"
export OPENMPI_PATH="/usr/lib64/openmpi"
