#!/bin/sh
volume=$(pamixer --get-volume-human | head -c 2)

if [[ "$volume" = "muted" ]]; then
    echo " muted"
elif [ "$volume" -gt 0 ] &&  [ "$volume" -le 33 ]; then
    echo " $volume%"
elif [ "$volume" -gt 33 ] && [ "$volume" -le 66 ]; then
    echo " $volume%"
elif [ "$volume" -gt 66 ] && [ "$volume" -le 100 ]; then
    echo " $volume%"
fi
